import { Room, Ticket, DayMeals, Notice, ShuttleRide, StudentPayment, StudentDetail } from './types';

export const INITIAL_ROOMS: Room[] = [
  {
    number: 'B-004',
    floor: 'Floor 0',
    floorId: 0,
    wing: 'South',
    type: 'AC',
    capacity: 2,
    occupied: 1,
    free: 1,
    status: 'Partially Occupied',
    students: ['Harsh'],
    lastCleaned: 'Today, 10:15 AM',
  },
  {
    number: 'ARV-301',
    floor: 'Floor 3',
    floorId: 3,
    wing: 'North',
    type: 'AC',
    capacity: 4,
    occupied: 2,
    free: 2,
    status: 'Partially Occupied',
    students: ['Aarav Sharma', 'Vikram Malhotra'],
    lastCleaned: 'Today, 10:30 AM',
  },
  {
    number: 'ARV-302',
    floor: 'Floor 3',
    floorId: 3,
    wing: 'North',
    type: 'AC',
    capacity: 3,
    occupied: 2,
    free: 1,
    status: 'Partially Occupied',
    students: ['Arjun Gill', 'Manish Paul'],
    lastCleaned: 'Today, 11:15 AM',
  },
  {
    number: 'ARV-303',
    floor: 'Floor 3',
    floorId: 3,
    wing: 'South',
    type: 'AC',
    capacity: 3,
    occupied: 1,
    free: 2,
    status: 'Partially Occupied',
    students: ['Kunal Sen'],
    lastCleaned: 'Yesterday, 04:30 PM',
  },
  {
    number: 'ARV-201',
    floor: 'Floor 2',
    floorId: 2,
    wing: 'West',
    type: 'Non-AC',
    capacity: 3,
    occupied: 3,
    free: 0,
    status: 'Reserved',
    students: ['Aditya Saxena', 'Gaurav Negi', 'Tushar B.'],
    lastCleaned: 'Today, 09:10 AM',
  },
  {
    number: 'ARV-202',
    floor: 'Floor 2',
    floorId: 2,
    wing: 'West',
    type: 'AC',
    capacity: 2,
    occupied: 1,
    free: 1,
    status: 'Partially Occupied',
    students: ['Zaid Khan'],
    lastCleaned: 'Today, 08:45 AM',
  },
  {
    number: 'ARV-203',
    floor: 'Floor 2',
    floorId: 2,
    wing: 'East',
    type: 'AC',
    capacity: 4,
    occupied: 4,
    free: 0,
    status: 'Fully Occupied',
    students: ['Pranav K.', 'Harsh V.', 'Dhruv S.', 'Ayush T.'],
    lastCleaned: 'Today, 01:20 PM',
  },
  {
    number: 'ARV-101',
    floor: 'Floor 1',
    floorId: 1,
    wing: 'North',
    type: 'Non-AC',
    capacity: 3,
    occupied: 0,
    free: 0,
    status: 'Under Maintenance',
    students: [],
    lastCleaned: '2 days ago',
  },
  {
    number: 'ARV-102',
    floor: 'Floor 1',
    floorId: 1,
    wing: 'North',
    type: 'Non-AC',
    capacity: 3,
    occupied: 2,
    free: 1,
    status: 'Partially Occupied',
    students: ['Rohan Varma', 'Kabir Mehta'],
    lastCleaned: 'Yesterday, 04:15 PM',
  },
  {
    number: 'ARV-103',
    floor: 'Floor 1',
    floorId: 1,
    wing: 'South',
    type: 'AC',
    capacity: 4,
    occupied: 4,
    free: 0,
    status: 'Fully Occupied',
    students: ['Devansh Roy', 'Sumit Roy', 'Anshul G.', 'Pateel N.'],
    lastCleaned: 'Today, 11:00 AM',
  },
  {
    number: 'ARV-G01',
    floor: 'Ground',
    floorId: 0,
    wing: 'South',
    type: 'Non-AC',
    capacity: 2,
    occupied: 1,
    free: 1,
    status: 'Partially Occupied',
    students: ['Siddharth Rao'],
    lastCleaned: 'Today, 08:30 AM',
  },
  {
    number: 'ARV-G02',
    floor: 'Ground',
    floorId: 0,
    wing: 'East',
    type: 'AC',
    capacity: 4,
    occupied: 4,
    free: 0,
    status: 'Fully Occupied',
    students: ['Nikhil J.', 'Faizan Q.', 'Rishi M.', 'Karan S.'],
    lastCleaned: 'Today, 09:40 AM',
  },
  {
    number: 'ARV-G03',
    floor: 'Ground',
    floorId: 0,
    wing: 'West',
    type: 'Non-AC',
    capacity: 2,
    occupied: 0,
    free: 2,
    status: 'Available',
    students: [],
    lastCleaned: 'Today, 07:15 AM',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'TCK-4091',
    hostelId: 'RP-BLK',
    email: 'upadhyayharshpritam@gmail.com',
    student: 'Harsh',
    room: 'B-004',
    subject: 'Thermostat dripping water continuously',
    category: 'Appliance / AC',
    status: 'In-Progress',
    timestamp: '15 mins ago',
    desc: 'The indoor AC thermostat unit is dripping condensate over the study desk. Needs coil drainage clearance and temperature sensor calibration.',
    urgency: 'High',
    assignedTechnician: 'Suresh Verma (Sr. HVAC Specialist)',
    assignedSlot: 'Today, 10:00 AM - 11:30 AM',
    wardenApproved: true,
    wardenApprovedAt: 'Today, 09:15 AM (Approved by Dr. Rajeshwardhan Singh)',
    resolutionNote: 'Technician dispatched with vacuum drainage pump, drip tray replacement seal, and digital temperature probe.',
    resolutionDispatchedAt: '10 mins ago',
    updates: [
      {
        id: 'up-1',
        sender: 'Warden',
        senderName: 'Dr. Rajeshwardhan Singh (Chief Warden)',
        message: 'Requisition verified. Priority HVAC job approved for immediate ground floor attendance.',
        timestamp: 'Today, 09:15 AM',
      },
      {
        id: 'up-2',
        sender: 'Admin',
        senderName: 'Facilities Maintenance Desk',
        message: 'Assigned Senior HVAC Technician Suresh Verma for slot 10:00 AM - 11:30 AM. Contact: +91 98112 00987.',
        timestamp: 'Today, 09:30 AM',
      },
    ],
    inspection: {
      isDone: false,
    },
    resolutionChecklist: [
      {
        id: 'chk-1',
        label: 'AC Condensate drain pipe vacuumed & free flowing with zero blockages',
        verifiedByResident: false,
      },
      {
        id: 'chk-2',
        label: 'Drip tray aligned and fresh watertight seal installed',
        verifiedByResident: false,
      },
      {
        id: 'chk-3',
        label: 'Cooling coil calibrated (airflow stable at 22°C test cycle)',
        verifiedByResident: false,
      },
      {
        id: 'chk-4',
        label: 'Study desk and work area wiped clean and dry',
        verifiedByResident: false,
      },
    ],
  },
  {
    id: 'TCK-4092',
    hostelId: 'RP-BLK',
    email: 'vikram.m@royalparadise.edu',
    student: 'Vikram Malhotra',
    room: 'RP-301',
    subject: 'Air Conditioner thermostat dripping water continuously',
    category: 'Appliance',
    status: 'Pending',
    timestamp: '12 mins ago',
    desc: 'The indoor unit is leaking water over desk #2. Compressor seems to freeze repeatedly. Potential electrical short hazard.',
    urgency: 'High',
  },
  {
    id: 'TCK-4089',
    hostelId: 'RP-BLK',
    email: 'aditya.s@royalparadise.edu',
    student: 'Aditya Saxena',
    room: 'RP-201',
    subject: 'WiFi Access Point intermittent latency & packet drops',
    category: 'Network',
    status: 'In-Progress',
    timestamp: '45 mins ago',
    desc: 'Wing South AP-04 keeps resetting every 7 minutes during project submissions. Bandwidth throttles to sub 0.5 Mbps.',
    urgency: 'Medium',
  },
  {
    id: 'TCK-4085',
    hostelId: 'RP-BLK',
    email: 'kabir.m@royalparadise.edu',
    student: 'Kabir Mehta',
    room: 'RP-102',
    subject: 'Bathroom flush valve malfunction & low pressure',
    category: 'Plumbing',
    status: 'Awaiting Approval',
    timestamp: '2 hours ago',
    desc: 'Main tank feed valve jammed. Water pressure too weak for secondary washroom in RP-102.',
    urgency: 'Normal',
    resolutionNote: 'Replaced primary intake spindle and descaled washroom pressure nozzle. Tested at full 2.5 bar pressure.',
    resolutionDispatchedAt: '1 hour ago',
  },
  {
    id: 'TCK-4072',
    hostelId: 'RP-BLK',
    email: 'aarav.s@royalparadise.edu',
    student: 'Aarav Sharma',
    room: 'RP-301',
    subject: 'Broken study chair hydraulic cylinder replacement',
    category: 'Carpentry',
    status: 'Resolved',
    timestamp: 'Yesterday',
    desc: 'Chair piston slipped completely downwards. Replacement cylinder installed by carpenter Mr. Ram Lal.',
    urgency: 'Low',
    resolutionNote: 'Heavy-duty Class 4 hydraulic piston installed and height adjustment lever calibrated.',
    resolutionDispatchedAt: 'Yesterday 16:30',
    studentApprovedAt: 'Yesterday 17:15',
    studentFeedback: 'Chair height adjustment is working perfectly now. Thank you for the quick replacement!',
  },
];

export const WEEKLY_MESS_MENU: Record<string, DayMeals> = {
  Mon: {
    Breakfast: 'Aloo Puri, Sabji, Tea',
    Lunch: 'Arhar Dal, Parwal Do Pyaza, Roti, Rice, Pickle, Salad',
    'Evening Snack': 'Samosa, Rasna',
    Dinner: 'Chana Dal, Aloo Gobhi, Kofta, Roti, Salad, Pickle',
  },
  Tue: {
    Breakfast: 'Sambar, Upma, Chutney, Tea',
    Lunch: 'Rajma, Aloo Matar, Rice, Roti, Pickle, Salad',
    'Evening Snack': 'Poha/Macaroni, Tea',
    Dinner: 'Puri Chola, Kaddu Ki Sabji, Kheer, Rice, Roti, Pickle, Salad',
  },
  Wed: {
    Breakfast: 'Aloo Paratha, Dahi, Tea',
    Lunch: 'Kadai Paneer, Kali Masoor Dal, Rice, Roti, Pickle, Salad',
    'Evening Snack': 'Aloo Bread Sandwich, Rasna',
    Dinner: 'Egg Curry/Malai Kofta, Rice, Roti, Salad, Gulab Jamun',
  },
  Thu: {
    Breakfast: 'Bread Butter Jam, Banana, Tea',
    Lunch: 'Mix Vegetable Sabzi, Punjabi Dal Tadka, Rice, Roti, Salad',
    'Evening Snack': 'Chow Mein, Tea',
    Dinner: 'Dal Makhani, Patta Gobhi Aloo, Seasonal Sabzi, Roti, Salad, Gulab Jamun',
  },
  Fri: {
    Breakfast: 'Pav Bhaji/Chole Kulcha, Tea',
    Lunch: 'Mix Vegetable Sabzi, Punjabi Dal, Rice, Roti, Pickle, Salad',
    'Evening Snack': 'Aloo Tikki Burger/Vegetable Burger, Tea',
    Dinner: 'Chilli Paneer, Veg Manchurian, Fried Rice, Roti, Salad',
  },
  Sat: {
    Breakfast: 'Kala Chana, Plain Paratha, Tea',
    Lunch: 'Vegetable Biryani, Chutney, Raita, Papad, Salad',
    'Evening Snack': 'Dahi Bhalla, Rasna',
    Dinner: 'Dal, Rice, Roti, Chana, Custard, Salad, Pickle',
  },
  Sun: {
    Breakfast: 'Paneer Paratha, Tea',
    Lunch: 'Chole Bhature, Rice, Raita, Pickle, Salad',
    'Evening Snack': 'Aloo Patties, Tea',
    Dinner: 'Chicken Curry, Paneer Do Pyaza, Rice, Roti, Salad, Pickle',
  },
};

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'NOT-901',
    title: 'Mandatory Semester Break Hostel Clearance Protocol',
    date: 'Oct 24, 2024',
    priority: 'High',
    target: 'All Residents',
    body: 'All students vacating Royal Paradise for the winter inter-semester recess must submit room keys to the Warden Office by 18:00 hrs on Friday. Electrical appliances must be disconnected.',
    author: 'Chief Warden Office',
  },
  {
    id: 'NOT-897',
    title: 'Scheduled Municipal Water Pipe Maintenance - Oct 27',
    date: 'Oct 22, 2024',
    priority: 'Medium',
    target: 'Royal Paradise All',
    body: 'Overhead secondary water reserves will undergo ultrasonic chemical descaling between 10:00 AM and 02:00 PM. Hot water geysers remain operational via backup lines.',
    author: 'Facilities Management',
  },
  {
    id: 'NOT-884',
    title: 'Annual Inter-Hostel Badminton Tournament Trials',
    date: 'Oct 19, 2024',
    priority: 'Normal',
    target: 'Sports Wing',
    body: "Registration slots for men's singles and doubles are currently open on campus portal. Trials commence Saturday 17:00 at Indoor Complex.",
    author: 'Hostel Sports Council',
  },
];

export const SHUTTLE_SCHEDULE: ShuttleRide[] = [
  {
    route: 'Royal Paradise -> Main Academic Quad',
    departure: '07:45 AM',
    arrival: '07:58 AM',
    busNo: 'BUS-01 (Ashok Leyland)',
    driver: 'Rameshwar Singh (+91 94112 00192)',
    status: 'On Time',
  },
  {
    route: 'Royal Paradise -> Science & Engg Labs',
    departure: '08:15 AM',
    arrival: '08:30 AM',
    busNo: 'BUS-04 (Tata Starbus)',
    driver: 'Harish Chandra (+91 94112 00195)',
    status: 'On Time',
  },
  {
    route: 'Main Quad -> Royal Paradise (Lunch run)',
    departure: '01:10 PM',
    arrival: '01:25 PM',
    busNo: 'BUS-01 (Ashok Leyland)',
    driver: 'Rameshwar Singh (+91 94112 00192)',
    status: 'Standby',
  },
  {
    route: 'Academic Quad -> Royal Paradise (Evening)',
    departure: '05:30 PM',
    arrival: '05:48 PM',
    busNo: 'BUS-02 (Eicher Electric)',
    driver: 'Santosh Kumar (+91 94112 00199)',
    status: 'Scheduled',
  },
  {
    route: 'Royal Paradise -> Metro Station Hub',
    departure: '07:00 PM',
    arrival: '07:22 PM',
    busNo: 'BUS-03 (Tata Wing)',
    driver: 'Mohd. Aslam (+91 94112 00188)',
    status: 'Scheduled',
  },
];

export const STUDENT_PAYMENTS: StudentPayment[] = [
  { name: 'Vikram Malhotra', room: 'ARV-301', dues: 12500, status: 'Overdue', lastPaymentDate: 'Aug 12, 2024' },
  { name: 'Kabir Mehta', room: 'ARV-102', dues: 6400, status: 'Overdue', lastPaymentDate: 'Sep 01, 2024' },
  { name: 'Aditya Saxena', room: 'ARV-201', dues: 15200, status: 'Overdue', lastPaymentDate: 'Jul 28, 2024' },
  { name: 'Aarav Sharma', room: 'ARV-301', dues: 0, status: 'Paid', lastPaymentDate: 'Oct 02, 2024' },
  { name: 'Devansh Roy', room: 'ARV-103', dues: 0, status: 'Paid', lastPaymentDate: 'Oct 01, 2024' },
  { name: 'Arjun Gill', room: 'ARV-302', dues: 0, status: 'Paid', lastPaymentDate: 'Sep 29, 2024' },
  { name: 'Siddharth Rao', room: 'ARV-G01', dues: 0, status: 'Paid', lastPaymentDate: 'Oct 04, 2024' },
];

export const STUDENT_DIRECTORY: Record<string, StudentDetail> = {
  'Harsh': {
    id: 'RES-HARSH-B004',
    name: 'Harsh',
    room: 'B-004',
    bed: 'Bed 1 (Ground Workstation)',
    college: 'IILM University',
    department: '',
    year: '1st Year',
    rollNo: 'RES-HARSH-B004',
    phone: '+91 8809900560',
    email: 'upadhyayharshpritam@gmail.com',
    guardian: 'xyz (Brother)',
    guardianPhone: '+91 98011 23456',
    bloodGroup: 'B+',
    homeCity: 'Patna, Bihar',
  },
  'Aarav Sharma': {
    id: 'STU-2023-019',
    name: 'Aarav Sharma',
    room: 'ARV-301',
    bed: 'Bed 1 (Window Lower)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BCSE042',
    phone: '+91 98711 20455',
    email: 'aarav.sharma@ait.edu.in',
    guardian: 'Ramesh Sharma (Father)',
    guardianPhone: '+91 98110 44210',
    bloodGroup: 'B+',
    homeCity: 'Chandigarh, Punjab',
  },
  'Vikram Malhotra': {
    id: 'STU-2023-088',
    name: 'Vikram Malhotra',
    room: 'ARV-301',
    bed: 'Bed 2 (Door Upper)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Electronics & Comm. Engg',
    year: '3rd Year · Sem 5',
    rollNo: '23BECE018',
    phone: '+91 98214 30981',
    email: 'vikram.m@ait.edu.in',
    guardian: 'Sunil Malhotra (Father)',
    guardianPhone: '+91 98200 11984',
    bloodGroup: 'O+',
    homeCity: 'Delhi NCR',
  },
  'Arjun Gill': {
    id: 'STU-2022-114',
    name: 'Arjun Gill',
    room: 'ARV-302',
    bed: 'Bed 1 (Study Alcove)',
    college: 'Aryabhatta School of Design & Tech',
    department: 'Information Science & AI',
    year: '4th Year · Sem 7',
    rollNo: '22BISA009',
    phone: '+91 97188 44021',
    email: 'arjun.gill@ait.edu.in',
    guardian: 'Harpreet Gill (Mother)',
    guardianPhone: '+91 97188 44000',
    bloodGroup: 'A+',
    homeCity: 'Ludhiana, Punjab',
  },
  'Manish Paul': {
    id: 'STU-2023-145',
    name: 'Manish Paul',
    room: 'ARV-302',
    bed: 'Bed 2 (Lower Bunk)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Mechanical Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BME076',
    phone: '+91 94500 81234',
    email: 'manish.paul@ait.edu.in',
    guardian: 'Dipankar Paul (Father)',
    guardianPhone: '+91 94500 81200',
    bloodGroup: 'AB+',
    homeCity: 'Kolkata, WB',
  },
  'Kunal Sen': {
    id: 'STU-2024-004',
    name: 'Kunal Sen',
    room: 'ARV-303',
    bed: 'Bed 1 (Balcony Corner)',
    college: 'School of Mathematics & Computing',
    department: 'Data Science & Analytics',
    year: '2nd Year · Sem 3',
    rollNo: '24BDSA015',
    phone: '+91 99102 77123',
    email: 'kunal.sen@ait.edu.in',
    guardian: 'Subhash Sen (Father)',
    guardianPhone: '+91 99102 77100',
    bloodGroup: 'O-',
    homeCity: 'Patna, Bihar',
  },
  'Aditya Saxena': {
    id: 'STU-2022-045',
    name: 'Aditya Saxena',
    room: 'ARV-201',
    bed: 'Bed 1 (Desk Side)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Electrical & Electronics',
    year: '4th Year · Sem 7',
    rollNo: '22BEEE031',
    phone: '+91 98390 12890',
    email: 'aditya.saxena@ait.edu.in',
    guardian: 'Alok Saxena (Father)',
    guardianPhone: '+91 98390 12800',
    bloodGroup: 'B+',
    homeCity: 'Lucknow, UP',
  },
  'Gaurav Negi': {
    id: 'STU-2022-092',
    name: 'Gaurav Negi',
    room: 'ARV-201',
    bed: 'Bed 2 (Upper Bunk)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Civil Infrastructure Engg',
    year: '4th Year · Sem 7',
    rollNo: '22BCIE024',
    phone: '+91 94120 55192',
    email: 'gaurav.negi@ait.edu.in',
    guardian: 'P.S. Negi (Father)',
    guardianPhone: '+91 94120 55100',
    bloodGroup: 'A-',
    homeCity: 'Dehradun, UK',
  },
  'Tushar B.': {
    id: 'STU-2022-108',
    name: 'Tushar B.',
    room: 'ARV-201',
    bed: 'Bed 3 (Door Side)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '4th Year · Sem 7',
    rollNo: '22BCSE112',
    phone: '+91 98101 66299',
    email: 'tushar.b@ait.edu.in',
    guardian: 'S. Bhattacharya (Father)',
    guardianPhone: '+91 98101 66200',
    bloodGroup: 'O+',
    homeCity: 'Gurugram, HR',
  },
  'Zaid Khan': {
    id: 'STU-2024-061',
    name: 'Zaid Khan',
    room: 'ARV-202',
    bed: 'Bed 1 (West Facing)',
    college: 'Aryabhatta School of Architecture',
    department: 'B.Arch Urban Planning',
    year: '2nd Year · Sem 3',
    rollNo: '24BARCH08',
    phone: '+91 97110 33418',
    email: 'zaid.khan@ait.edu.in',
    guardian: 'Tariq Khan (Father)',
    guardianPhone: '+91 97110 33400',
    bloodGroup: 'B-',
    homeCity: 'Bhopal, MP',
  },
  'Pranav K.': {
    id: 'STU-2023-201',
    name: 'Pranav K.',
    room: 'ARV-203',
    bed: 'Bed 1 (Lower Right)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BCSE091',
    phone: '+91 98450 11982',
    email: 'pranav.k@ait.edu.in',
    guardian: 'K. Narayanan (Father)',
    guardianPhone: '+91 98450 11900',
    bloodGroup: 'O+',
    homeCity: 'Bengaluru, KA',
  },
  'Harsh V.': {
    id: 'STU-2023-202',
    name: 'Harsh V.',
    room: 'ARV-203',
    bed: 'Bed 2 (Upper Right)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BCSE092',
    phone: '+91 98450 22983',
    email: 'harsh.v@ait.edu.in',
    guardian: 'V. Raman (Father)',
    guardianPhone: '+91 98450 22900',
    bloodGroup: 'A+',
    homeCity: 'Hyderabad, TS',
  },
  'Dhruv S.': {
    id: 'STU-2023-203',
    name: 'Dhruv S.',
    room: 'ARV-203',
    bed: 'Bed 3 (Lower Left)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Information Science & AI',
    year: '3rd Year · Sem 5',
    rollNo: '23BISA044',
    phone: '+91 98450 33984',
    email: 'dhruv.s@ait.edu.in',
    guardian: 'Satish Sharma (Father)',
    guardianPhone: '+91 98450 33900',
    bloodGroup: 'B+',
    homeCity: 'Jaipur, RJ',
  },
  'Ayush T.': {
    id: 'STU-2023-204',
    name: 'Ayush T.',
    room: 'ARV-203',
    bed: 'Bed 4 (Upper Left)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Electronics & Comm. Engg',
    year: '3rd Year · Sem 5',
    rollNo: '23BECE055',
    phone: '+91 98450 44985',
    email: 'ayush.t@ait.edu.in',
    guardian: 'M. Tiwari (Father)',
    guardianPhone: '+91 98450 44900',
    bloodGroup: 'AB+',
    homeCity: 'Varanasi, UP',
  },
  'Rohan Varma': {
    id: 'STU-2024-012',
    name: 'Rohan Varma',
    room: 'ARV-102',
    bed: 'Bed 1 (Study Bay)',
    college: 'Aryabhatta School of Management',
    department: 'Integrated BBA-MBA Fintech',
    year: '2nd Year · Sem 3',
    rollNo: '24BBA022',
    phone: '+91 99201 88471',
    email: 'rohan.varma@ait.edu.in',
    guardian: 'Ajay Varma (Father)',
    guardianPhone: '+91 99201 88400',
    bloodGroup: 'O+',
    homeCity: 'Mumbai, MH',
  },
  'Kabir Mehta': {
    id: 'STU-2024-033',
    name: 'Kabir Mehta',
    room: 'ARV-102',
    bed: 'Bed 2 (Lower Corner)',
    college: 'School of Mathematics & Computing',
    department: 'Applied Mathematics & Stats',
    year: '2nd Year · Sem 3',
    rollNo: '24BMTH014',
    phone: '+91 98119 77201',
    email: 'kabir.mehta@ait.edu.in',
    guardian: 'Nitin Mehta (Father)',
    guardianPhone: '+91 98119 77200',
    bloodGroup: 'A+',
    homeCity: 'Ahmedabad, GJ',
  },
  'Devansh Roy': {
    id: 'STU-2023-066',
    name: 'Devansh Roy',
    room: 'ARV-103',
    bed: 'Bed 1 (Lower Bay)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Biotechnology & Bio-Engg',
    year: '3rd Year · Sem 5',
    rollNo: '23BBT011',
    phone: '+91 98300 44129',
    email: 'devansh.roy@ait.edu.in',
    guardian: 'Soumitra Roy (Father)',
    guardianPhone: '+91 98300 44100',
    bloodGroup: 'B+',
    homeCity: 'Kolkata, WB',
  },
  'Sumit Roy': {
    id: 'STU-2023-067',
    name: 'Sumit Roy',
    room: 'ARV-103',
    bed: 'Bed 2 (Upper Bay)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Chemical Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BCHE029',
    phone: '+91 98300 55130',
    email: 'sumit.roy@ait.edu.in',
    guardian: 'Soumitra Roy (Father)',
    guardianPhone: '+91 98300 44100',
    bloodGroup: 'B+',
    homeCity: 'Kolkata, WB',
  },
  'Anshul G.': {
    id: 'STU-2023-068',
    name: 'Anshul G.',
    room: 'ARV-103',
    bed: 'Bed 3 (Door Lower)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Aerospace Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BAERO019',
    phone: '+91 94140 66201',
    email: 'anshul.g@ait.edu.in',
    guardian: 'R.K. Gupta (Father)',
    guardianPhone: '+91 94140 66200',
    bloodGroup: 'O+',
    homeCity: 'Kota, RJ',
  },
  'Pateel N.': {
    id: 'STU-2023-069',
    name: 'Pateel N.',
    room: 'ARV-103',
    bed: 'Bed 4 (Door Upper)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Mechanical Engineering',
    year: '3rd Year · Sem 5',
    rollNo: '23BME088',
    phone: '+91 98230 77312',
    email: 'pateel.n@ait.edu.in',
    guardian: 'V. Patel (Father)',
    guardianPhone: '+91 98230 77300',
    bloodGroup: 'A+',
    homeCity: 'Pune, MH',
  },
  'Siddharth Rao': {
    id: 'STU-2024-118',
    name: 'Siddharth Rao',
    room: 'ARV-G01',
    bed: 'Bed 1 (Ground Lower)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '1st Year · Sem 1',
    rollNo: '25BCSE004',
    phone: '+91 98490 88219',
    email: 'siddharth.rao@ait.edu.in',
    guardian: 'G.V. Rao (Father)',
    guardianPhone: '+91 98490 88200',
    bloodGroup: 'O+',
    homeCity: 'Visakhapatnam, AP',
  },
  'Nikhil J.': {
    id: 'STU-2024-121',
    name: 'Nikhil J.',
    room: 'ARV-G02',
    bed: 'Bed 1 (North Bunk)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Information Science & AI',
    year: '1st Year · Sem 1',
    rollNo: '25BISA029',
    phone: '+91 98111 99012',
    email: 'nikhil.j@ait.edu.in',
    guardian: 'Manoj Joshi (Father)',
    guardianPhone: '+91 98111 99000',
    bloodGroup: 'B+',
    homeCity: 'Noida, UP',
  },
  'Faizan Q.': {
    id: 'STU-2024-122',
    name: 'Faizan Q.',
    room: 'ARV-G02',
    bed: 'Bed 2 (South Bunk)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Computer Science & Engineering',
    year: '1st Year · Sem 1',
    rollNo: '25BCSE058',
    phone: '+91 98722 33419',
    email: 'faizan.q@ait.edu.in',
    guardian: 'A. Qureshi (Father)',
    guardianPhone: '+91 98722 33400',
    bloodGroup: 'O-',
    homeCity: 'Aligarh, UP',
  },
  'Rishi M.': {
    id: 'STU-2024-123',
    name: 'Rishi M.',
    room: 'ARV-G02',
    bed: 'Bed 3 (East Bunk)',
    college: 'Aryabhatta Institute of Technology',
    department: 'Electronics & Comm. Engg',
    year: '1st Year · Sem 1',
    rollNo: '25BECE041',
    phone: '+91 98311 44521',
    email: 'rishi.m@ait.edu.in',
    guardian: 'P.K. Mishra (Father)',
    guardianPhone: '+91 98311 44500',
    bloodGroup: 'AB+',
    homeCity: 'Ranchi, JH',
  },
  'Karan S.': {
    id: 'STU-2024-124',
    name: 'Karan S.',
    room: 'ARV-G02',
    bed: 'Bed 4 (West Bunk)',
    college: 'School of Design & Computing',
    department: 'Human-Computer Interaction',
    year: '1st Year · Sem 1',
    rollNo: '25BHCI012',
    phone: '+91 98200 66782',
    email: 'karan.s@ait.edu.in',
    guardian: 'J.S. Sethi (Father)',
    guardianPhone: '+91 98200 66700',
    bloodGroup: 'A+',
    homeCity: 'Amritsar, PB',
  },
};

export const getStudentDetails = (name: string, roomNumber: string, index: number = 0): StudentDetail => {
  if (STUDENT_DIRECTORY[name]) {
    return STUDENT_DIRECTORY[name];
  }
  // Fallback dynamic profile generator
  const cleanName = name.trim();
  const initials = cleanName.split(' ').map(n => n[0]).join('').toUpperCase();
  return {
    id: `STU-2024-${100 + index * 7}`,
    name: cleanName,
    room: roomNumber,
    bed: `Bed #${index + 1}`,
    college: 'Aryabhatta Institute of Technology',
    department: '',
    year: 'Undergraduate Resident',
    rollNo: `24BTECH${initials}${10 + index}`,
    phone: '+91 98110 000' + (10 + index),
    email: `${cleanName.toLowerCase().replace(/\s+/g, '.')}@ait.edu.in`,
    guardian: 'Guardian of ' + cleanName,
    guardianPhone: '+91 98110 999' + (10 + index),
    bloodGroup: 'B+',
    homeCity: 'Campus Resident',
  };
};

